### PR TITLE
second of a serie of three

### PR DESCRIPTION
**Pull request by stappersg**
This commit message is written with `git commit`. It is text for
co-workers and future self. Previous commit was #4 and full URL
is https://github.com/n8henrie/killed-9-example/pull/4

New alinea, contains also #4 and
URL https://github.com/n8henrie/killed-9-example/pull/4

### CODE REVIEW

**Comment by stappersg** [comment]
```text
$ git commit
[twototango 022070d] second of a serie of three
 1 file changed, 3 insertions(+)
$ git show
commit 022070d66924afbfeffb6113c5ec569fceec953b (HEAD -> twototango)
Author: Geert Stappers <stappers@stappers.it>
Date:   Mon Jun 13 13:35:57 2022 +0200

    second of a serie of three
    
    This commit message is written with `git commit`. It is text for
    co-workers and future self. Previous commit was #4 and full URL
    is https://github.com/n8henrie/killed-9-example/pull/4
    
    New alinea, contains also #4 and
    URL https://github.com/n8henrie/killed-9-example/pull/4

diff --git a/test.txt b/test.txt
index dd5c66f..3f79b96 100644
--- a/test.txt
+++ b/test.txt
@@ -9,3 +9,6 @@ We are at the begin of long journey, good AVR+Rust.
 There is some friction, at least I feel some friction.
 That (possible) friction shouldn't exist,
 it will damage the project we both care about.
+
+What is the short term goal?
+Better understanding of "git commit message" versus "github PR text".
$
```

Before the _merge request_ was created:
```text
$ git push
fatal: The current branch twototango has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin twototango

$ git push --set-upstream origin twototango
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 529 bytes | 529.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: 
remote: Create a pull request for 'twototango' on GitHub by visiting:
remote:      https://github.com/stappersg/killed-9-example/pull/new/twototango
remote: 
To github.com:stappersg/killed-9-example.git
 * [new branch]      twototango -> twototango
branch 'twototango' set up to track 'origin/twototango'.
$ 
```
And at  https://github.com/stappersg/killed-9-example/pull/new/twototango two clicks, no text entry.

**Comment by stappersg** [comment]
Thing I expect is that only
```text
    second of a serie of three
    
    This commit message is written with `git commit`. It is text for
    co-workers and future self. Previous commit was #4 and full URL
    is https://github.com/n8henrie/killed-9-example/pull/4
```
will show up in `git log` at _main branch_.  That the second alinea will get eaten by _github.com_.

**Comment by n8henrie** [comment]
I assume you also want me to make a merge commit for these?

I'm not sure what you mean by `alinea`, or what you're trying to demonstrate, because your pull request message and commit message look virtually identical. If you're interested in examining which parts of what end up in the git repo, I would recommend making clearly distinct / easily distinguishable pull request vs commit message, instead of "two clicks, no text entry."

For example, `git commit -m "this is from my commit message"`, then make a pull request and change the body to `this is from my pull request`. Then, after merging, you could easily `git log --grep 'this is from'` and see what shows up.

**Comment by stappersg** [comment]
> I assume you also want me to make a merge commit for these?

Correct. And (upcoming) number three please also.

**Pull request merged**
